### ISSUE TITLE
チャンネル一覧api

### ISSUE THREAD

**Issue by syougo1209** [givery-bootcamp/dena-2024-team2#3]
### 元のIssue

https://github.com/givery-bootcamp/training-app-2024/issues/2

### 領域

バックエンド

### 説明

- チャンネルの一覧を api を作成する
- テーブル `Channels` を定義する
  - id
  - server id
  - name
- endpoint: `GET /channels`
- parameter: ひとまず、なし
- response: Channels のエンティティ配列
  - ソートはひとまず id 降順
- 認証: 不要

### 受入条件

- [ ] 仕様をすべて満たしている
- [ ] テストが記述されている
- [ ] テストがすべて成功している
- [ ] コードが適切にフォーマットされている

**Comment by TakanoHori** [comment]
| COLUMN_NAME  | TYPE | |
| ------------- | ------------- | ------------- |
| id  | int  | PRIMARY KEY |
| server_id  | int  | |
| name  | varchar(XX) | |
| created_at | datetime | |
| updated_at | datetime | |
| deleted_at | datetime | |
