### ISSUE TITLE
チャンネル内の投稿一覧api

### ISSUE THREAD

**Issue by syougo1209** [givery-bootcamp/dena-2024-team2#4]
### 元のIssue

https://github.com/givery-bootcamp/training-app-2024/issues/3

### 領域

バックエンド

### 説明

チャンネル内の投稿一覧api

### 受入条件

- [ ] 仕様をすべて満たしている
- [ ] テストが記述されている
- [ ] テストがすべて成功している
- [ ] コードが適切にフォーマットされている

**Comment by TakanoHori** [comment]
終わっているタスクのためクローズ。
