### ISSUE TITLE
signupするときにsignin状態にする

### ISSUE THREAD

**Issue by syougo1209** [givery-bootcamp/dena-2024-team2#40]
### 元のIssue

多分ない

### 領域

バックエンド

### 説明

signupのapiを読んだときにsignin状態にできるようにjwtを返すように修正する

### 受入条件

- [ ] 仕様をすべて満たしている
- [ ] テストが記述されている
- [ ] テストがすべて成功している
- [ ] コードが適切にフォーマットされている

**Comment by TakanoHori** [comment]
ユーザーまわりが kotlin に移行したので、一旦クローズ
