### ISSUE TITLE
サインアップAPIの実装

### ISSUE THREAD

**Issue by syougo1209** [givery-bootcamp/dena-2024-team2#7]
### 元のIssue

[usersテーブルのpasswordカラムをHash値に変更する #41](https://github.com/givery-bootcamp/training-app-2024/issues/41)

### 領域

バックエンド

### 説明

- ユーザーがサインアップするためのAPIを実装する
- サインインは実装しなくて良い（別のIssue）
- まずは、平文で登録できるようにした上で、Hash値に変更する

### 受入条件

- [ ] 仕様をすべて満たしている
- [ ] テストが記述されている
- [ ] テストがすべて成功している
- [ ] コードが適切にフォーマットされている

**Comment by TakanoHori** [comment]
Golang で Hash を使うには、`bcrypt` が良さそう。
https://pkg.go.dev/golang.org/x/crypto/bcrypt

**Comment by TakanoHori** [comment]
参考記事
- [goでパスワードを平文ではなくハッシュ化して保存し、ログインまで行う](https://qiita.com/osamu_0/items/e747921cce4ca9e48720)
- [【Go】bcrypt を使ってパスワードのハッシュ値を生成して検証する](https://zenn.dev/kou_pg_0131/articles/go-digest-and-compare-by-bcrypt)

**Comment by TakanoHori** [comment]
パスワードが平文で保存されていることを確認する
```
dena-2024-team2 % docker-compose exec db mysql training

mysql> select * from users;
+----+--------+----------+---------------------+---------------------+------------+
| id | name   | password | created_at          | updated_at          | deleted_at |
+----+--------+----------+---------------------+---------------------+------------+
|  1 | taro   | password | 2024-06-11 13:16:48 | 2024-06-11 13:16:48 | NULL       |
|  2 | hanako | PASSWORD | 2024-06-11 13:16:48 | 2024-06-11 13:16:48 | NULL       |
+----+--------+----------+---------------------+---------------------+------------+
2 rows in set (0.00 sec)
```
